plugins {
    id 'net.minecraftforge.gradle' version '6.0.24'
    id 'java'
}

sourceSets {
    main {
        resources {
            srcDir 'src/main/resources'
        }
    }
}

group = 'com.sakalti'
archivesBaseName = 'sakalti'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

minecraft {
    mappings channel: 'official', version: '1.20.1'

    runs {
        client {
            workingDirectory project.file('run')
        }
        server {
            workingDirectory project.file('run')
        }
    }
}

repositories {
    maven {
        name = 'forge'
        url = 'https://maven.minecraftforge.net/'
    }
    maven {
        name = 'blamejared'
        url = 'https://maven.blamejared.com/'
    }
    maven {
        name = 'CurseMaven'
        url = 'https://cursemaven.com'
    }
    mavenCentral()
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.5'
    compileOnly fg.deobf("curse.maven:mantle-74924:7563777")
    
    // Tinkers' Construct を最新版に更新
    compileOnly fg.deobf("curse.maven:tinkers-construct-74072:7449219")
}

jar {
    manifest {
        attributes(
            'Specification-Title': 'sakalti',
            'Specification-Vendor': 'sakalti',
            'Specification-Version': '1.0.0',
            'Implementation-Title': project.name,
            'Implementation-Version': project.version,
            'Implementation-Vendor': 'sakalti'
        )
    }
}

processResources {
    duplicatesStrategy = 'INCLUDE'
}
