modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="sakalti"
version="1.0.0"
displayName="TConX"
authors="お方"
description='''
TConXはテスト用MODです。Forge 1.20.1対応。
'''
displayURL="https://github.com/maikuran/Tconx"

[[dependencies.sakalti]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.sakalti]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
